language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-precise-3.8
    - george-edison55-precise-backports
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libboost1.55-all-dev
    - g++-4.8
    - clang-3.8
    - doxygen
    - graphviz
    - graphviz-dev
    - cmake
    - cmake-data
    - gcc-5
    - g++-5
    - gcc-6
    - g++-6

matrix:
  include:
    - compiler: gcc
      env: BUILD_TYPE="Release"
    - compiler: gcc
      env: BUILD_TYPE="DebugAS"
    - compiler: gcc
      env: BUILD_TYPE="DebugTS"
    - compiler: gcc
      env: BUILD_TYPE="DebugUBS"
    - compiler: gcc
      env: BUILD_TYPE="Coverage"
    - compiler: clang
      env: BUILD_TYPE="Release"
    - compiler: clang
      env: BUILD_TYPE="Debug"

install:
    - if [[ "${CC}" == "clang" ]]; then
          export MPPP_COMPILER=clang;
          export CC=clang-3.8;
          export CXX=clang++-3.8;
      elif [[ "${BUILD_TYPE}" == "Coverage" ]]; then
          export MPPP_COMPILER=gcc;
          export CC=gcc-5;
          export CXX=g++-5;
          export GCOV_EXECUTABLE=gcov-5;
      elif [[ "${CC}" == "gcc" && "${BUILD_TYPE}" == "Release" ]]; then
          export MPPP_COMPILER=gcc;
          export CC=gcc-4.8;
          export CXX=g++-4.8;
      else
          export MPPP_COMPILER=gcc;
          export CC=gcc-6;
          export CXX=g++-6;
      fi
script:
    - mkdir build
    - cd build
    - source ../tools/install_travis.sh

notifications:
  email: false
