language: cpp

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - libgmp-dev
    - libmpfr-dev
    - cmake
    - cmake-data

matrix:
  include:
    - env: MPPP_BUILD="ReleaseGCC48"
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
          - g++-4.8
    - env: MPPP_BUILD="DebugGCC48"
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
          - g++-4.8
    - env: MPPP_BUILD="CoverageGCC5"
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
          - gcc-5
          - g++-5
    - env: MPPP_BUILD="DebugClang39"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.9
          packages:
          - clang-3.9
    - env: MPPP_BUILD="ReleaseClang39"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.9
          packages:
          - clang-3.9

script:
    - mkdir build
    - cd build
    - source ../tools/install_travis.sh

notifications:
  email: false
