language: cpp

sudo: false

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: /pr\/.*/

matrix:
  include:
    - env: MPPP_BUILD="ReleaseGCC48"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - g++-4.8
          - libgmp-dev
          - libmpfr-dev
          - cmake
          - cmake-data
    - env: MPPP_BUILD="DebugGCC48"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - g++-4.8
          - libgmp-dev
          - libmpfr-dev
          - cmake
          - cmake-data
    - env: MPPP_BUILD="DebugGCC48DebugGMP"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - g++-4.8
          - cmake
          - cmake-data
    - env: MPPP_BUILD="CoverageGCC5"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-5
          - g++-5
          - libgmp-dev
          - libmpfr-dev
          - cmake
          - cmake-data
    - env: MPPP_BUILD="Coverage32GCC6"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-multilib
          - g++-multilib
          - gcc-6
          - gcc-6-multilib
          - g++-6
          - g++-6-multilib
          - cmake
          - cmake-data
    - env: MPPP_BUILD="DebugClang38"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.8
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - clang-3.8
          - libgmp-dev
          - libmpfr-dev
          - cmake
          - cmake-data
    - env: MPPP_BUILD="ReleaseClang38"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.8
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - clang-3.8
          - libgmp-dev
          - libmpfr-dev
          - cmake
          - cmake-data

script:
    - mkdir build
    - cd build
    - source ../tools/install_travis.sh

notifications:
  email: false
