language: cpp

sudo: false

# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: /pr\/.*/

# env:
#   global:
#     - secure: "XVtnE3+rh2VtRdv9/vzpo69pGGgR8xHks6MKdAeCmdxBfMZpOXkfmZ5S9QGsVSvlbZjSkfc9QbFxGj3VVaYPciULTW4zyXZj09LzkWOTDVPu5VBT6oz6/iWH5vOoFVvMAUWb3uhRDL8q1FuIcbzQ5HhszWs2Yvjidf1+GpahAIlnHvkqM6dKJLBsHgNq9CWcf/D2GkGFBdS6LoT6p2WDOzl0aCy2dI89c9TRzXA978hhq5avtGmO9sZpqCVaI/IikZPEILML1uxmTamUKKsUFK/x3WU3eo/hYAtlqE4f0Uv8/Y6Als+mNAXeS2ok/GKAHbcW1S7LqT+GbgB2mJr6CTpiMKFZf1XCJGC4Ml8V2Kh4aZQjncwxzvPf0DDrGM6jLQP0Ya/5EVCtbr/IFZwbcApoVngGkUB/viopK7QoEultODDW3bp7UZo4/Rh6+P1WAvnK7d2qQXInQRRllQM3f5wWsEA40H2HoTnm9iPTDQUVFwlWnNSxQvRnhXk9RCDQDBDAWz1Sg5Uv5YeCYgvQAuDtHisBX2FLHK7Y2EgsX/hap8/+rOlluGamUgeVqiuP3Hox8ypTmqHE0f46azgjKwV6HbQTQHnthpfiTWOW0mRqE5zxNeYFfqfsF9T5pvGL3Fnoo68aaEz/7nqq2PdgaL0NtGZofGxifSqQ+zas8wQ="

matrix:
  include:
    - env: MPPP_BUILD="ReleaseGCC48"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - g++-4.8
          - libgmp-dev
          - libmpfr-dev
          - cmake
          - cmake-data
    - env: MPPP_BUILD="DebugGCC48"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - g++-4.8
          - libgmp-dev
          - libmpfr-dev
          - cmake
          - cmake-data
    - env: MPPP_BUILD="DebugGCC48DebugGMP"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - g++-4.8
          - cmake
          - cmake-data
    - env: MPPP_BUILD="CoverageGCC5"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-5
          - g++-5
          - libgmp-dev
          - libmpfr-dev
          - cmake
          - cmake-data
    - env: MPPP_BUILD="Coverage32GCC6"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - gcc-multilib
          - g++-multilib
          - gcc-6
          - gcc-6-multilib
          - g++-6
          - g++-6-multilib
          - cmake
          - cmake-data
    - env: MPPP_BUILD="DebugClang38"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.8
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - clang-3.8
          - libgmp-dev
          - libmpfr-dev
          - cmake
          - cmake-data
    - env: MPPP_BUILD="ReleaseClang38"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.8
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - clang-3.8
          - libgmp-dev
          - libmpfr-dev
          - cmake
          - cmake-data
    # - env: MPPP_BUILD="ICC" DOCKER_IMAGE="bluescarni/icc_ci:v1"
    #   sudo: required
    #   services:
    #   - docker
script:
    - mkdir build
    - cd build
    - source ../tools/install_travis.sh

notifications:
  email: false
