version: '{build}'

environment:
  global:
    PLATFORMTOOLSET: "v140"

  matrix:
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      PLATFORM: Win32
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      PLATFORM: x64

install:
# Set path and download deps.
- if [%COMPILER%]==[MSVC15] set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[x64] call tools\appveyor-download.cmd https://github.com/bluescarni/binary_deps/raw/master/mppp_deps_msvc_64.7z
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[Win32] call tools\appveyor-download.cmd https://github.com/bluescarni/binary_deps/raw/master/mppp_deps_msvc_32.7z
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[x64] 7z x mppp_deps_msvc_64.7z > NUL
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[Win32] 7z x mppp_deps_msvc_32.7z > NUL

build_script:
- mkdir build
- cd build

- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[Win32] cmake -G "Visual Studio 14 2015" -DMPPP_BUILD_TESTS=YES -DGMP_INCLUDE_DIR=C:/mppp_deps_32/mpir -DGMP_LIBRARY=C:/mppp_deps_32/mpir/mpir.lib ..
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[x64] cmake -G "Visual Studio 14 2015 Win64" -DMPPP_BUILD_TESTS=YES -DGMP_INCLUDE_DIR=C:/mppp_deps_64/mpir -DGMP_LIBRARY=C:/mppp_deps_64/mpir/mpir.lib ..

- cmake --build . --config %BUILD_TYPE% --target ALL_BUILD

test_script:
- ctest --output-on-failure

# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, use the login information that the line below
# prints into the log.
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
