version: '{build}'

environment:
  global:
    PLATFORMTOOLSET: "v140"

  matrix:
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      PLATFORM: Win32
    - BUILD_TYPE: Debug
      COMPILER: MSVC15
      PLATFORM: x64
    - BUILD_TYPE: Debug
      COMPILER: MinGW
      PLATFORM: x64

install:
# Set path and download deps for MSVC.
- if [%COMPILER%]==[MSVC15] set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[x64] call tools\appveyor-download.cmd https://github.com/bluescarni/binary_deps/raw/master/mppp_deps_msvc_64.7z
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[Win32] call tools\appveyor-download.cmd https://github.com/bluescarni/binary_deps/raw/master/mppp_deps_msvc_32.7z
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[x64] 7z x -oC:\ mppp_deps_msvc_64.7z > NUL
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[Win32] 7z x -oC:\ mppp_deps_msvc_32.7z > NUL
# Same for MinGW.
- if [%COMPILER%]==[MinGW] set PATH=C:\mingw64\bin;%PATH%
- if [%COMPILER%]==[MinGW] call tools\appveyor-download.cmd https://github.com/bluescarni/binary_deps/raw/master/x86_64-6.2.0-release-posix-seh-rt_v5-rev1.7z
- if [%COMPILER%]==[MinGW] 7z x -oC:\ x86_64-6.2.0-release-posix-seh-rt_v5-rev1.7z > NUL
- if [%COMPILER%]==[MinGW] if [%PLATFORM%]==[x64] call tools\appveyor-download.cmd https://github.com/bluescarni/binary_deps/raw/master/mppp_deps_mingw_64.7z
- if [%COMPILER%]==[MinGW] if [%PLATFORM%]==[x64] 7z x -oC:\ mppp_deps_mingw_64.7z > NUL
# Rename sh.exe as sh.exe in PATH interferes with MinGW.
- if [%COMPILER%]==[MinGW] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"

build_script:
- mkdir build
- cd build

- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[Win32] cmake -G "Visual Studio 14 2015" -DMPPP_BUILD_TESTS=YES -DGMP_INCLUDE_DIR=C:/mppp_deps_32/mpir -DGMP_LIBRARY=C:/mppp_deps_32/mpir/mpir.lib ..
- if [%COMPILER%]==[MSVC15] if [%PLATFORM%]==[x64] cmake -G "Visual Studio 14 2015 Win64" -DMPPP_BUILD_TESTS=YES -DGMP_INCLUDE_DIR=C:/mppp_deps_64/mpir -DGMP_LIBRARY=C:/mppp_deps_64/mpir/mpir.lib ..
- if [%COMPILER%]==[MSVC15] cmake --build . --config %BUILD_TYPE% --target ALL_BUILD
- if [%COMPILER%]==[MinGW] if [%PLATFORM%]==[x64] cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DMPPP_BUILD_TESTS=YES -DMPPP_WITH_LONG_DOUBLE=YES -DGMP_INCLUDE_DIR=C:/mppp_deps_64/gmp -DGMP_LIBRARY=C:/mppp_deps_64/gmp/libgmp.a -DMPFR_INCLUDE_DIR=C:/mppp_deps_64/mpfr -DMPFR_LIBRARY=C:/mppp_deps_64/mpfr/libmpfr.a ..
#- if [%COMPILER%]==[MinGW] cmake --build . --config %BUILD_TYPE% --target all
- if [%COMPILER%]==[MinGW] mingw32-make -j2

test_script:
- ctest -V

# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, use the login information that the line below
# prints into the log.
# on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
