version: 2

jobs:
  bionic_gcc7_conda_coverage:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_conda_coverage.sh
  bionic_gcc7_conda_release:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_conda_release.sh
  focal_gcc9_conda_coverage:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_gcc9_conda_coverage.sh
  focal_clang9_conda_tsan:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_clang9_conda_tsan.sh
  focal_clang9_debuggmp_unstable:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_clang9_debuggmp_unstable.sh
  focal_clang9_debuggmp:
    docker:
    - image: circleci/buildpack-deps:focal
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_focal_clang9_debuggmp.sh
  bionic_gcc7_conda_asan:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_conda_asan.sh
  bionic_gcc7_conda_ubsan:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_conda_ubsan.sh

workflows:
  version: 2
  all_builds:
    jobs:
    - bionic_gcc7_conda_coverage
    - bionic_gcc7_conda_release
    - focal_gcc9_conda_coverage
    - focal_clang9_conda_tsan
    - focal_clang9_debuggmp_unstable
    - focal_clang9_debuggmp
    - bionic_gcc7_conda_asan
    - bionic_gcc7_conda_ubsan
